services:
  - type: web
    name: financial-chatbot-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - fromGroup: financial-chatbot

  - type: web
    name: financial-chatbot-app
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    envVars:
      - fromGroup: financial-chatbot
