from ..agents import OrchestratorAgent
from ..repositories.document import DocumentRepository
from ..repositories.financial import FinancialRepository


class AgentService:
    def __init__(
        self,
        document_repo: DocumentRepository,
        financial_repo: FinancialRepository,
    ):
        self.document_repo = document_repo
        self.financial_repo = financial_repo
        self.agent = OrchestratorAgent(
            document_repo=self.document_repo,
            financial_repo=self.financial_repo,
        )
    
    def ask_question(self, q: str):
        """
        Asks the agent a question and streams the final answer as it is generated.

        Args:
            main_question (str): The main question to be asked.

        Returns:
            AsyncGenerator: An asynchronous generator that yields the partial answer generated by the agent as it is being streamed.
        """
        return self.agent.ask_question_stream(main_question=q)
