from typing import Annotated

from fastapi import Query
from starlette.responses import StreamingResponse

from ....services.agent import AgentService


class AgentController:
    def __init__(
        self,
        agent_svc: AgentService,
    ):
        self.agent_svc = agent_svc

    async def ask_question(
        self,
        q: Annotated[str, Query()],
    ):
        """
        Asks the agent a question and streams the final answer as it is generated.

        Args:
            q (str): The main question to be asked.

        Yields:
            str: The partial answer generated by the agent as it is being streamed.
        """

        return StreamingResponse(
            content=self.agent_svc.ask_question(q),
            media_type="text/plain; charset=utf-8",
        )
